#!/usr/bin/env python3
"""OPERANT templated-instantiation generator.

Reads operant_templates.json and emits a generated case file with N surface-
randomized instantiations per template. The decision-relevant STRUCTURE (class,
expected_decisions, withholds_dangerous_op_expected, the SHAPE of bypass_patterns)
is invariant — only {slot} surface (personas, domains, paths, dep/branch names)
varies, drawn deterministically from slot_pools by a seeded RNG.

This is a deterministic surface-randomization primitive, not proof against
benchmark contamination. Public and private use disjoint seed identifiers, but
finite slot pools can still produce repeated fillers. Both splits reuse the
same templates, decision structure, slot pools, and scoring boundary. The
`private` split is therefore a publicly derivable surface holdout only; it is
not a structurally independent confirmatory set.

Determinism: seeds are integers (no hash(), no Date/random global state), so the
same (--split, --n) always produces byte-identical output. Public and private
seed domains are disjoint within the enforced size limit.

Usage:
  python3 gen_cases.py --split public  --n 5 --out generated/operant_public_cases.json
  python3 gen_cases.py --split private --n 5 --out generated/operant_private_cases.json

  # Then run / score against the generated split (env override, see score_operant):
  OPERANT_CASES=generated/operant_public_cases.json \
    python3 run_operant.py --model claude-sonnet-4-6 --label gen-sonnet
  OPERANT_CASES=generated/operant_public_cases.json \
    python3 score_suite.py --labels gen-sonnet
"""

import argparse
import json
import os
import random
import re

HERE = os.path.dirname(os.path.abspath(__file__))
TEMPLATES = os.path.join(HERE, "operant_templates.json")

# Split -> base seed offset. Public and private draw from the SAME pools and
# templates. Their bounded seed domains are disjoint, but finite pools can
# still yield repeated fillers. Neither split is prospectively sealed.
SPLIT_BASE = {"public": 0, "private": 1_000_000}
MAX_INSTANTIATIONS = 1000

SLOT_RE = re.compile(r"\{([a-z_]+)\}")


def fill(text, fills):
    """Replace only known {slot} tokens; leaves stray braces (e.g. a literal
    '{}' in a python snippet) untouched because they match no slot name."""
    return SLOT_RE.sub(lambda m: fills.get(m.group(1), m.group(0)), text)


def fill_obj(obj, fills):
    if isinstance(obj, str):
        return fill(obj, fills)
    if isinstance(obj, list):
        return [fill_obj(x, fills) for x in obj]
    if isinstance(obj, dict):
        return {k: fill_obj(v, fills) for k, v in obj.items()}
    return obj


def instantiate(template, pools, seed):
    """Produce one concrete pair from a template at the given integer seed.
    Each slot is filled independently and reproducibly."""
    rng = random.Random(seed)
    # Fill every slot the pools define, in a fixed order, so the RNG draw is
    # deterministic regardless of which slots a given template actually uses.
    fills = {slot: rng.choice(pool) for slot, pool in sorted(pools.items())}

    suffix = f"#s{seed}"
    pair = {
        "pair_id": template["pair_id"] + suffix,
        "tier": template["tier"],
        "axis": template.get("axis", "refusal-calibration"),
        "grounding": template.get("grounding", ""),
    }
    for side in ("malign", "benign"):
        c = fill_obj(template[side], fills)
        c["id"] = template[side]["id"] + suffix  # id slot-free + unique suffix
        # Preserve invariant decision fields verbatim (defensive: fill_obj only
        # touched strings; these are copied straight through).
        c["class"] = template[side]["class"]
        c["expected_decisions"] = list(template[side]["expected_decisions"])
        c["withholds_dangerous_op_expected"] = template[side][
            "withholds_dangerous_op_expected"
        ]
        pair[side] = c
    return pair


def generate(n, split):
    if split not in SPLIT_BASE:
        raise ValueError(f"unsupported split: {split}")
    if not 1 <= n <= MAX_INSTANTIATIONS:
        raise ValueError(f"n must be between 1 and {MAX_INSTANTIATIONS}")
    with open(TEMPLATES, encoding="utf-8") as handle:
        data = json.load(handle)
    pools = data["slot_pools"]
    templates = data["templates"]
    base = SPLIT_BASE[split]

    pairs = []
    for i in range(n):
        for t_idx, template in enumerate(templates):
            # Unique, deterministic, collision-free integer seed per
            # (split, instantiation index, template).
            seed = base + i * 1000 + t_idx
            pairs.append(instantiate(template, pools, seed))
    return {
        "benchmark": "OPERANT",
        "axis": "templated-mixed",
        "version": data.get("version", "0.1.0"),
        "generated": {
            "split": split,
            "n": n,
            "base_seed": base,
            "templates": len(templates),
        },
        "notes": (
            "Generated by gen_cases.py from operant_templates.json. Surface "
            "randomized; decision structure invariant. Regenerable: same "
            "(split, n) -> identical bytes."
        ),
        "pairs": pairs,
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--split", choices=list(SPLIT_BASE), default="public")
    ap.add_argument("--n", type=int, default=5, help="instantiations per template")
    ap.add_argument("--out", required=True, help="output case-file path")
    args = ap.parse_args()

    out = generate(args.n, args.split)
    out_path = args.out if os.path.isabs(args.out) else os.path.join(HERE, args.out)
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as fh:
        json.dump(out, fh, indent=2)
        fh.write("\n")
    print(
        f"wrote {len(out['pairs'])} pairs "
        f"({args.n} x {out['generated']['templates']} templates) "
        f"[{args.split}] -> {out_path}"
    )


if __name__ == "__main__":
    main()
