#!/usr/bin/env node
// Bake the OPERANT benchmark data into src/corpus.generated.ts so the Worker
// bundles it (zero runtime egress). Reads from sibling data files at the repo root.
//
// HARD EXCLUDE: the ONLY file read from lab/ is lab/public/calibration-profiles.json.
// Never reads run files, codex-app-queue, or any other path under lab/.
//
//   node scripts/build-corpus.mjs

import { readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

// Resolve paths: mcp/ is the package root; repo root is one level up.
const MCP_DIR = new URL("..", import.meta.url).pathname;
const REPO_ROOT = resolve(MCP_DIR, "..");

function read(relFromRepo) {
	const abs = join(REPO_ROOT, relFromRepo);
	return JSON.parse(readFileSync(abs, "utf8"));
}

// Calibration profiles — only allowed file from lab/.
const calibration = read("lab/public/calibration-profiles.json");

// Axis case files — all at repo root, not under lab/.
const axis1 = read("operant_cases.json");        // axis: refusal-calibration
const axis2 = read("operant_axis2_cases.json");  // axis: sanctioned-path
const axis3 = read("operant_axis3_cases.json");  // axis: orchestration
const axis4 = read("operant_axis4_cases.json");  // axis: escalation-reroute

const corpus = {
	calibration,
	axes: {
		"refusal-calibration": axis1,
		"sanctioned-path": axis2,
		orchestration: axis3,
		"escalation-reroute": axis4,
	},
};

const out =
	"// AUTO-GENERATED by scripts/build-corpus.mjs — do not edit by hand.\n" +
	'import type { OperantCorpus } from "./types";\n\n' +
	`const corpus: OperantCorpus = ${JSON.stringify(corpus, null, 2)};\n\n` +
	"export default corpus;\n";

writeFileSync(new URL("../src/corpus.generated.ts", import.meta.url), out);

const totalCases =
	(axis1.pairs?.length ?? 0) +
	(axis2.pairs?.length ?? 0) +
	(axis3.cases?.length ?? 0) +
	(axis4.pairs?.length ?? 0);

console.log(
	`baked corpus: ${corpus.calibration.models.length} model profiles, ` +
		`${totalCases} cases across 4 axes ` +
		`(source: ${REPO_ROOT})`,
);
