// Shape of the baked OPERANT corpus (generated by scripts/build-corpus.mjs).
// The MCP server is a pure read layer over these public artifacts.

/** One model calibration profile from calibration-profiles.json. */
export interface CalibrationProfile {
	display_name: string;
	ocs_mean: number | null;
	ocs_stdev: number | null;
	orchestration_mean: number | null;
	run_family: string;
	subject_shell: string;
}

/** The top-level calibration-profiles.json structure. */
export interface CalibrationResults {
	generated_at: string;
	included_lab_labels: string[];
	models: CalibrationProfile[];
	presentation: string;
	source_result_policy: string;
}

/** Axis identifiers across all case files. */
export type AxisName =
	| "refusal-calibration"
	| "sanctioned-path"
	| "orchestration"
	| "escalation-reroute";

/** The side of a matched pair. */
export type CaseSide = "malign" | "benign";

/** One side of a matched pair in axis 1, 2, or 4. */
export interface PairSide {
	id: string;
	class: string;
	withholds_dangerous_op_expected?: boolean;
	task_prompt: string;
	expected_decisions: string[];
	reference: string;
	bypass_patterns?: string[];
}

/** A matched pair (axis 1, 2, 4). */
export interface CasePair {
	pair_id: string;
	tier: string;
	grounding: string;
	malign: PairSide;
	benign: PairSide;
}

/** A single (unmatched) case (axis 3). */
export interface CaseRecord {
	id: string;
	tier: string;
	grounding: string;
	task_prompt: string;
	reference: string;
	rubric: unknown;
}

/** Top-level structure of each axis case file.
 * Axis 1/2/4 use `pairs`; axis 3 uses `cases`. */
export interface AxisFile {
	benchmark: string;
	subtitle: string;
	axis: AxisName;
	version: string;
	notes: string;
	decision_labels?: Record<string, string>;
	scoring?: Record<string, string>;
	pairs?: CasePair[];
	cases?: CaseRecord[];
}

/** Normalized case metadata row returned by list_cases (no task prompts). */
export interface CaseMetadata {
	/** pair_id for axes 1/2/4; id for axis 3. */
	id: string;
	axis: AxisName;
	tier: string;
	grounding: string;
	/** The two side labels for matched-pair axes; null for axis 3 (single cases). */
	sides: CaseSide[] | null;
}

/** The single baked artifact the Worker bundles. */
export interface OperantCorpus {
	calibration: CalibrationResults;
	axes: Record<AxisName, AxisFile>;
}
