// AUTO-GENERATED by scripts/build-wellknown.mjs — do not edit by hand.
// The signed discovery manifest, served verbatim by the Worker at
// /.well-known/mcp.json (+ .sig and the Ed25519 public key).

export const MANIFEST_JSON = "{\n\t\"name\": \"operant-mcp\",\n\t\"title\": \"OPERANT · MCP server\",\n\t\"description\": \"Read-only MCP server over the OPERANT AI operating-agent calibration benchmark: model results, methodology, and the case library. Stateless streamable HTTP, zero runtime egress, every tool read-only.\",\n\t\"site\": \"https://operant.saagarpatel.dev\",\n\t\"registry\": \"io.github.saagpatel/operant-mcp\",\n\t\"repository\": \"https://github.com/saagpatel/operant\",\n\t\"mcp_server\": {\n\t\t\"status\": \"live\",\n\t\t\"endpoint\": \"https://operant.saagarpatel.dev/mcp\",\n\t\t\"transport\": \"streamable-http\",\n\t\t\"authentication\": \"none\",\n\t\t\"tools\": [\n\t\t\t\"get_results\",\n\t\t\t\"compare_models\",\n\t\t\t\"get_methodology\",\n\t\t\t\"list_cases\",\n\t\t\t\"get_case\"\n\t\t],\n\t\t\"resources\": [\"operant://results\", \"operant://methodology\"],\n\t\t\"prompts\": [\"score_my_agent\"]\n\t},\n\t\"packages\": [\n\t\t{\n\t\t\t\"registry\": \"npm\",\n\t\t\t\"identifier\": \"saagar-operant-mcp\",\n\t\t\t\"runtime\": \"npx\"\n\t\t}\n\t]\n}\n";

export const MANIFEST_SIG = "UFwgH1zJMt1wKzk0D0bVz/ryQj5q+nYW4qT6iOr1yfxEKnadOX0d+sJhQV/96VFsxVaCqcE2AUtP/2bvrbFBDA==\n";

export const MANIFEST_PUBKEY = "-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEA7WJ0Dtv2uYJZoXVJJZ/d51PIqCxuBJ8L4unLVILXVhc=\n-----END PUBLIC KEY-----\n";
